- name: cart
  hosts: cart
  become: yes
  tasks: 
    - name: disable nodejs 
      ansible.builtin.dnf: 
        name: nodejs 
        state: absent

    - name: enable nodejs
      ansible.builtin.dnf: 
        name: 'nodejs:18'
        state: present 

    - name: add user roboshop 
      ansible.builtin.user: 
        name: roboshop 

    - name: remove app directory 
      ansible.builtin.file: 
        path: /app 
        state: absent 

    - name: app directory 
      ansible.builtin.file: 
        path: /app
        state: directory 
    
    - name: download application code 
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/cart.zip
        dest: /tmp 

    - name: unzip user.zip 
      ansible.builtin.unarchive: 
        src: /tmp/cart.zip 
        dest: /app
        remote_src: yes 

    - name: download dependencies 
      ansible.builtin.command: npm install 
      args: 
        chdir: /app 

    - name: cart.service in systemd 
      ansible.builtin.copy: 
        src: /cart.service
        dest: /etc/systemd/system/cart.service
        remote_src: yes 

    - name: sytemctl daemon reload 
      ansible.builtin.systemd_service:
        daemon_reload: true 
    
    - name: start and enable 
      ansible.builtin.service:
        name: user 
        state: restarted
        enabled: yes 
