- name: mysql 
  become: yes
  hosts: mysql 
  tasks: 
    - name: disable mysql 
      ansible.builtin.dnf: 
        name: mysql 
        state: absent 
    
    - name: copy to mysql.repo 
      ansible.builtin.copy: 
        src: /mysql.repo
        dest: /etc/yum.repos.d/mysql.repo

    - name: install mysql server 
      ansible.builtin.dnf: 
        name: mysql-community-server
        state: present 

    - name: start and enable mysql 
      ansible.builtin.service: 
        name: mysqld
        state: present 
        enabled: yes 

    - name: change default root password 
      ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1 