- name: shipping 
  become: yes 
  hosts: shipping 
  vars: 
    mysql_password: RoboShop@1
  tasks: 
    - name: install maven 
      ansible.builtin.dnf: 
        name: maven 
        state: present 

    - name: create a user 
      ansible.builtin.user: 
        name: roboshop 

    - name: delete app directory 
      ansible.builtin.file:
        path: /app 
        state: absent 

    - name: create a directory 
      ansible.builtin.file: 
        path: /app
        state: directory

    - name: download application code 
      ansible.builtin.get_url:
         url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
         dest: /tmp 

    - name: unarchive 
      ansible.builtin.unarchive: 
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes 

    - name: clean package 
      ansible.builtin.command: mvn clean package
      args: 
        chdir: /app  

    - name: rename jar file  
      ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
      args: 
        chdir: /app

    - name: copy shipping service 
      ansible.builtin.copy:
        src: shipping.service 
        dest: /etc/systemd/system/shipping.service
        remote_src: yes 

    - name: Restart service 
      ansible.builtin.systemd_service:
        daemon_reload: true
    
    - name: Restart service 
      ansible.builtin.systemd_service:
        state: restarted
        name: shipping 
        enable: true 

    - name: install mysql 
      ansible.builtin.dnf: 
        name: mysql 
        state: present  

    - name: check cities schema exists or not
      ansible.builtin.command:  mysql -h mysql.aws2day.online -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'"
      register: schema

    - name: print output
      ansible.builtin.debug:
        msg: "schema output: {{schema}}"

    - name: load schema 
      ansible.builtin.command: mysql -h mysql.aws2day.online -uroot -p{{mysql_password}} < /app/schema/shipping.sql 
      when: schema.stdout !="1"
      
    - name: restart 
      ansible.builtin.service: 
        name: shipping
        state: restarted 